# Generated by Django 5.2.7 on 2025-10-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foodinspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInsecurityForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_id', models.CharField(max_length=32)),
                ('state_name', models.CharField(blank=True, default='', max_length=64)),
                ('state_abbreviation', models.CharField(blank=True, default='', max_length=4)),
                ('year', models.PositiveIntegerField()),
                ('overall_food_insecurity_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('child_food_insecurity_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('estimated_food_insecure_individuals', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_food_insecure_children', models.PositiveIntegerField(blank=True, null=True)),
                ('low_income_household_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('high_income_household_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('low_type_code', models.IntegerField(blank=True, null=True)),
                ('high_type_code', models.IntegerField(blank=True, null=True)),
                ('raw_features', models.JSONField(blank=True, default=dict)),
                ('centroid_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_insecurity_forecasts', to='app.locationzone')),
            ],
            options={
                'ordering': ('-year', 'state_abbreviation', 'district_id'),
                'unique_together': {('district_id', 'year')},
            },
        ),
    ]
