# Generated by Django 5.2.7 on 2025-10-09 03:05

from datetime import timedelta
from decimal import Decimal

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aidprogram_donation_locationzone_aidrecommendation_and_more'),
    ]

    def _create_seed_data(apps, schema_editor):
        User = apps.get_model('app', 'User')
        LocationZone = apps.get_model('app', 'LocationZone')
        Donation = apps.get_model('app', 'Donation')
        FamilyProfile = apps.get_model('app', 'FamilyProfile')
        Claim = apps.get_model('app', 'Claim')
        Notification = apps.get_model('app', 'Notification')
        AidProgram = apps.get_model('app', 'AidProgram')
        AidRecommendation = apps.get_model('app', 'AidRecommendation')

        now = timezone.now()

        family_user, _ = User.objects.get_or_create(
            email='family@example.com',
            defaults={
                'first_name': 'Alicia',
                'last_name': 'Rivera',
                'role': 'family',
                'is_active': True,
                'password': make_password('FreshBayDemo!1'),
            },
        )

        FamilyProfile.objects.get_or_create(
            user=family_user,
            defaults={
                'phone_number': '415-555-2024',
                'zip_code': '94107',
                'household_size': 4,
                'dietary_preferences': ['fresh produce', 'low sodium'],
                'notes': 'Prefers pickups after 5pm.',
            },
        )

        soma_zone, _ = LocationZone.objects.get_or_create(
            name='SoMa Community Hub',
            defaults={
                'level': 'medium',
                'households_supported': 120,
                'latitude': Decimal('37.778520'),
                'longitude': Decimal('-122.405640'),
            },
        )

        bayview_zone, _ = LocationZone.objects.get_or_create(
            name='Bayview Food Collective',
            defaults={
                'level': 'high',
                'households_supported': 240,
                'latitude': Decimal('37.729510'),
                'longitude': Decimal('-122.382240'),
            },
        )

        Donation.objects.update_or_create(
            title='Organic Produce Crates',
            donor_name='Harborview Grocers',
            defaults={
                'category': 'produce',
                'freshness_notes': 'Picked this morning',
                'distance_miles': Decimal('2.5'),
                'available_from': now - timedelta(hours=2),
                'available_until': now + timedelta(hours=6),
                'quantity': 15,
                'status': 'available',
                'location_zone': soma_zone,
                'is_prediction': False,
            },
        )

        ready_donation, _ = Donation.objects.update_or_create(
            title='Family Meal Kits',
            donor_name='Neighborhood Kitchen',
            defaults={
                'category': 'prepared',
                'freshness_notes': 'Contains signature veggie lasagna',
                'distance_miles': Decimal('3.1'),
                'available_from': now - timedelta(days=1),
                'available_until': now + timedelta(hours=2),
                'quantity': 8,
                'status': 'ready',
                'location_zone': bayview_zone,
                'is_prediction': False,
            },
        )

        Donation.objects.update_or_create(
            title='Weekly Dairy Delivery',
            donor_name='Sunrise Farms',
            defaults={
                'category': 'dairy',
                'freshness_notes': 'Includes lactose-free options',
                'distance_miles': Decimal('5.0'),
                'available_from': now + timedelta(hours=12),
                'available_until': now + timedelta(days=1),
                'quantity': 20,
                'status': 'predicted',
                'location_zone': soma_zone,
                'is_prediction': True,
            },
        )

        Claim.objects.update_or_create(
            user=family_user,
            donation=ready_donation,
            defaults={
                'status': 'reserved',
                'reserved_at': now - timedelta(hours=3),
                'pickup_window_start': now + timedelta(hours=1),
                'pickup_window_end': now + timedelta(hours=3),
                'verification_code': 'FB-482913',
            },
        )

        Notification.objects.update_or_create(
            user=family_user,
            message='Pickup window opens soon for Family Meal Kits.',
            defaults={
                'notification_type': 'upcoming',
                'scheduled_for': now + timedelta(minutes=30),
            },
        )

        Notification.objects.update_or_create(
            user=family_user,
            message='Share feedback from last week’s produce share.',
            defaults={
                'notification_type': 'info',
                'scheduled_for': now - timedelta(days=1),
            },
        )

        AidProgram.objects.update_or_create(
            name='Fresh Families Grocery Credit',
            defaults={
                'summary': 'Monthly stipend for families buying fresh produce at partner markets.',
                'steps': 'Confirm eligibility → Submit proof of residence → Enroll via outreach partner',
                'external_url': 'https://example.org/fresh-families',
                'tags': ['produce', 'monthly support'],
            },
        )

        AidProgram.objects.update_or_create(
            name='Neighborhood Pantry Express',
            defaults={
                'summary': 'Scheduled weekly deliveries of pantry staples and fresh goods.',
                'steps': 'Choose delivery slot → Confirm household size → Receive doorstep delivery',
                'external_url': 'https://example.org/pantry-express',
                'tags': ['delivery', 'weekly'],
            },
        )

        AidRecommendation.objects.update_or_create(
            user=family_user,
            title='Apply for Fresh Families Grocery Credit',
            defaults={'reason': 'You qualify for produce-focused assistance in your neighborhood.'},
        )

        AidRecommendation.objects.update_or_create(
            user=family_user,
            title='Schedule Neighborhood Pantry Express delivery',
            defaults={'reason': 'Matches your preferred pickup times and household size.'},
        )

    def _remove_seed_data(apps, schema_editor):
        User = apps.get_model('app', 'User')
        LocationZone = apps.get_model('app', 'LocationZone')
        Donation = apps.get_model('app', 'Donation')
        FamilyProfile = apps.get_model('app', 'FamilyProfile')
        Claim = apps.get_model('app', 'Claim')
        Notification = apps.get_model('app', 'Notification')
        AidProgram = apps.get_model('app', 'AidProgram')
        AidRecommendation = apps.get_model('app', 'AidRecommendation')

        email = 'family@example.com'
        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            user = None

        if user:
            AidRecommendation.objects.filter(user=user).delete()
            Notification.objects.filter(user=user).delete()
            Claim.objects.filter(user=user).delete()
            FamilyProfile.objects.filter(user=user).delete()

        AidProgram.objects.filter(
            name__in=[
                'Fresh Families Grocery Credit',
                'Neighborhood Pantry Express',
            ]
        ).delete()

        Donation.objects.filter(
            title__in=[
                'Organic Produce Crates',
                'Family Meal Kits',
                'Weekly Dairy Delivery',
            ]
        ).delete()

        LocationZone.objects.filter(
            name__in=[
                'SoMa Community Hub',
                'Bayview Food Collective',
            ]
        ).delete()

        if user:
            user.delete()

    operations = [migrations.RunPython(_create_seed_data, _remove_seed_data)]
