# Generated by Django 5.2.7 on 2025-10-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def sync_max_pickups(apps, schema_editor):
    Donation = apps.get_model('app', 'Donation')
    for donation in Donation.objects.all().only('id', 'quantity', 'max_pickups'):
        donation.max_pickups = donation.quantity or 0
        donation.save(update_fields=['max_pickups'])


def reverse_sync_max_pickups(apps, schema_editor):
    Donation = apps.get_model('app', 'Donation')
    for donation in Donation.objects.all().only('id', 'max_pickups', 'quantity'):
        if donation.max_pickups:
            donation.quantity = donation.max_pickups
            donation.save(update_fields=['quantity'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_seed_demo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='max_pickups',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(sync_max_pickups, reverse_sync_max_pickups),
    ]
