# Generated by Django 5.2.7 on 2025-10-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_donorprofile_donorteammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='next_pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='volunteers_needed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
