# Generated by Django 5.2.7 on 2025-10-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_foodinsecurityforecast'),
        ('app', '0009_donation_pickup_location'),
    ]

    operations = [
    ]
